import type { Agent, AgentCatalog, AgentRow } from '@/services/api/types';

/** A full agent as the API returns it (Phase 5 UI tests). */
export const fakeAgent = (overrides: Partial<Agent> = {}): Agent => ({
  id: 'a1',
  name: 'Recovery Bot',
  description: 'Overdue EMI follow-up',
  persona: 'Aap Demo Finance ki recovery assistant hain.',
  openingLine: 'Namaste {{name}} ji',
  closingLine: 'Dhanyavaad',
  isActive: true,
  templateKey: 'loan_recovery_hinglish',
  allowedVariables: ['name'],
  voice: 'coral',
  languageMode: 'auto',
  language: 'hinglish',
  toneRules: [{ when: 'angry', customWhen: null, respond: 'Main samajh sakta hoon.' }],
  callBehaviour: {
    maxCallDurationSec: 300,
    silenceTimeoutSec: 8,
    bargeIn: true,
    endCallAfterSilenceRetries: 2,
  },
  model: { textModel: 'gpt-4.1-mini', temperatureTenths: 6, maxOutputTokens: 300 },
  limits: { dailySpendCapMicros: 0, monthlySpendCapMicros: 0, onCap: 'fallback' },
  guardrails: {
    neverSay: ['legal notice'],
    disclosureLine: 'Main AI assistant hoon.',
    complianceMode: 'recovery',
  },
  fallback: {
    aiFailed: 'Maaf kijiye, technical dikkat hai.',
    walletEmpty: 'Service abhi uplabdh nahi hai.',
    agentOff: 'Agent band hai.',
    capReached: 'Aaj ke liye seva band hai.',
  },
  knowledge: { knowledgeBaseIds: [], topK: 4, minScoreHundredths: 35 },
  functions: [],
  builtInTools: {
    endCall: { enabled: true },
    transferToHuman: { enabled: false, phone: null, message: null },
    setDisposition: { enabled: true, allowed: ['paid', 'promise_to_pay'] },
    scheduleCallback: { enabled: false, maxDaysAhead: 7 },
    savePromiseToPay: { enabled: true, maxDaysAhead: 15 },
    sendSmsAfterCall: { enabled: false, templates: [] },
  },
  createdBy: 'u1',
  updatedBy: 'u1',
  createdAt: '2026-10-09T00:00:00.000Z',
  updatedAt: '2026-10-09T00:00:00.000Z',
  ...overrides,
});

export const fakeAgentRow = (overrides: Partial<AgentRow> = {}): AgentRow => ({
  id: 'a1',
  name: 'Recovery Bot',
  description: 'Overdue EMI follow-up',
  isActive: true,
  voice: 'coral',
  languageMode: 'auto',
  language: 'hinglish',
  knowledgeBases: 1,
  functions: 1,
  monthSpendMicros: 1_250_000,
  updatedAt: '2026-10-09T00:00:00.000Z',
  ...overrides,
});

export const FAKE_CATALOG: AgentCatalog = {
  provider: 'fake',
  voices: ['alloy', 'coral', 'sage'],
  languages: ['hi', 'en', 'hinglish'],
  toneTriggers: ['angry', 'confused', 'sad', 'in_a_hurry', 'abusive', 'custom'],
  dispositions: [
    'paid',
    'promise_to_pay',
    'callback_requested',
    'wrong_number',
    'refused_to_pay',
    'dispute',
    'not_interested',
    'language_barrier',
    'other',
  ],
  builtInTools: [
    'end_call',
    'transfer_to_human',
    'set_disposition',
    'schedule_callback',
    'save_promise_to_pay',
    'send_sms_after_call',
  ],
  textModels: ['gpt-4.1-mini', 'gpt-4.1'],
  defaultTextModel: 'gpt-4.1-mini',
  variables: [
    { name: 'name', label: 'Name', type: 'built_in' },
    { name: 'phone_last4', label: 'Last 4 digits of the phone', type: 'built_in' },
    { name: 'loan_amount', label: 'Loan amount', type: 'currency' },
  ],
  limits: { functionsPerAgent: 10, kbPerAgent: 3, personaMaxChars: 8000, messageMaxChars: 2000 },
};
