// AUTO-GENERATED by `npm run gen:api` from the backend OpenAPI spec — do not edit.
// Source of truth: cell-ai-voicebot-backend/openapi/openapi.json (ADR 0029).

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — the process is up (no dependency checks) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Alive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['Health'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness — MongoDB and Redis reachable and not shutting down */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ready */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['Readiness'];
            };
          };
        };
        /** @description A dependency is down or the server is shutting down (PROVIDER_UNAVAILABLE) */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/system/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Service name, version and runtime */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description App info */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AppInfo'];
            };
          };
        };
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDetail: {
      /** @example phone */
      path: string;
      /** @example Must be an E.164 number */
      message: string;
    };
    ErrorEnvelope: {
      /** @enum {boolean} */
      success: false;
      error: {
        /** @example VALIDATION_FAILED */
        code: string;
        /** @example Some fields are invalid. */
        message: string;
        details?: components['schemas']['ErrorDetail'][];
        /** @example req_8f2c1a */
        requestId: string;
      };
    };
    OffsetPageMeta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
    CursorPageMeta: {
      nextCursor: string | null;
      hasMore: boolean;
    };
    Health: {
      /** @enum {string} */
      status: 'ok';
      /** @example 3600 */
      uptimeSec: number;
    };
    Readiness: {
      /** @enum {string} */
      status: 'ready';
      /**
       * @example {
       *       "mongo": "up",
       *       "redis": "up"
       *     }
       */
      checks: {
        [key: string]: 'up';
      };
    };
    AppInfo: {
      /** @example cell-ai-voicebot-backend */
      name: string;
      /** @example 0.0.1 */
      version: string;
      /** @example v24.19.0 */
      node: string;
      /** @example development */
      env: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
