// AUTO-GENERATED by `npm run gen:api` from the backend OpenAPI spec — do not edit.
// Source of truth: cell-ai-voicebot-backend/openapi/openapi.json (ADR 0029).

export interface paths {
  '/api/v1/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create an account + owner; sends a 6-digit email code (always 202) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @example Demo Finance */
            businessName: string;
            /** @example Asha Verma */
            name: string;
            /**
             * Format: email
             * @example asha@example.com
             */
            email: string;
            /** Format: password */
            password: string;
            phone?: string;
            /** @example Asia/Kolkata */
            timezone?: string;
          };
        };
      };
      responses: {
        /** @description Accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Accepted'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm the email code and sign in */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: email
             * @example asha@example.com
             */
            email: string;
            /** @example 042917 */
            code: string;
          };
        };
      };
      responses: {
        /** @description Signed in. Sets the httpOnly `cav_rt` refresh cookie (Path=/api/v1/auth, SameSite=Strict). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthSession'];
            };
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign in with email + password (5 failures in 15 min → 429) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: email
             * @example asha@example.com
             */
            email: string;
            /** Format: password */
            password: string;
          };
        };
      };
      responses: {
        /** @description Signed in. Sets the httpOnly `cav_rt` refresh cookie (Path=/api/v1/auth, SameSite=Strict). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthSession'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** New access token from the refresh cookie (rotates the cookie; reuse revokes the session) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Signed in. Sets the httpOnly `cav_rt` refresh cookie (Path=/api/v1/auth, SameSite=Strict). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthSession'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End the cookie session (idempotent, clears the cookie) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign out of every session (all access tokens stop working) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user, account, role, permissions and impersonation info */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthMe'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update your own name / phone */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name?: string;
            phone?: string | null;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthMe'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Active sessions of the current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['Session'][];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke one of your sessions */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify-email/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a new email code (always 202; 60 s cooldown, 5 per hour) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: email
             * @example asha@example.com
             */
            email: string;
          };
        };
      };
      responses: {
        /** @description Accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Accepted'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email a password reset link (always 202) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: email
             * @example asha@example.com
             */
            email: string;
          };
        };
      };
      responses: {
        /** @description Accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Accepted'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set a new password from a reset link (ends every session) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            token: string;
            /** Format: password */
            password: string;
          };
        };
      };
      responses: {
        /** @description Password changed */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Accepted'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change your password (other sessions end; returns new tokens for this one) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthSession'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Your account and its settings (account.read) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['PublicAccount'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update account settings (account.update) — nested settings are merged */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name?: string;
            /** @example Asia/Kolkata */
            timezone?: string;
            country?: string;
            /** @enum {string} */
            defaultLanguage?: 'hi' | 'en' | 'hinglish';
            settings?: {
              /**
               * @example {
               *       "start": "09:00",
               *       "end": "19:00",
               *       "days": [
               *         1,
               *         2,
               *         3,
               *         4,
               *         5,
               *         6
               *       ]
               *     }
               */
              callingWindow?: {
                start: string;
                end: string;
                days: number[];
              };
              recordingEnabled?: boolean;
              aiDisclosureEnabled?: boolean;
            };
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['PublicAccount'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit log of the account, newest first (audit.read, cursor pagination) */
    get: {
      parameters: {
        query?: {
          cursor?: string;
          limit?: number;
          actorId?: string;
          action?: string;
          targetType?: string;
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Entries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuditEntry'][];
              meta: components['schemas']['CursorPageMeta'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** All customer accounts (superadmin) */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          status?: 'active' | 'suspended';
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accounts */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AdminAccountRow'][];
              meta: components['schemas']['OffsetPageMeta'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Account detail with owner, user counts and recent audit (superadmin) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AdminAccountDetail'];
            };
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts/{id}/suspend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suspend an account — it becomes read-only (superadmin) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            reason: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['PublicAccount'];
            };
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts/{id}/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Re-enable a suspended account (superadmin) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['PublicAccount'];
            };
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/accounts/{id}/impersonate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** View as the account owner for 30 minutes (no refresh cookie; audited) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthSession'];
            };
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/impersonation/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End an impersonation session (call with the impersonation token) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/api-keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** API keys of the account (apikeys.read) — never the key itself */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['ApiKey'][];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    /** Create an API key (apikeys.manage; max 20 active). The full key is returned once. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            name: string;
            scopes: (
              | 'calls:read'
              | 'calls:write'
              | 'contacts:read'
              | 'contacts:write'
              | 'campaigns:read'
              | 'campaigns:write'
              | 'webhooks:manage'
            )[];
          };
        };
      };
      responses: {
        /** @description Created (Cache-Control: no-store) */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['CreatedApiKey'];
            };
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/api-keys/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke an API key (idempotent) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/api-keys/whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Check an API key (X-API-Key) — account, key id and scopes */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: {
                accountId: string;
                apiKeyId: string;
                scopes: string[];
              };
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — the process is up (no dependency checks) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Alive */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['Health'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness — MongoDB and Redis reachable and not shutting down */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ready */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['Readiness'];
            };
          };
        };
        /** @description A dependency is down or the server is shutting down (PROVIDER_UNAVAILABLE) */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rbac/permissions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Permission catalogue and built-in roles */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['RbacCatalog'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/ws/tickets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Single-use 60 s ticket for wss://…/ws/events?ticket=… (30 / min per user) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * @default events
             * @enum {string}
             */
            channel?: 'events';
          };
        };
      };
      responses: {
        /** @description Ticket */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['WsTicket'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/team/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Team members + pending invites (team.read) */
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          status?: 'invited' | 'active' | 'disabled';
          roleKey?: 'owner' | 'admin' | 'manager' | 'agent' | 'viewer';
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Members */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['TeamMember'][];
              meta: components['schemas']['OffsetPageMeta'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/team/invites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invite a member by email (team.invite; only the owner can invite admins) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /**
             * Format: email
             * @example asha@example.com
             */
            email: string;
            name: string;
            /** @enum {string} */
            roleKey: 'admin' | 'manager' | 'agent' | 'viewer';
          };
        };
      };
      responses: {
        /** @description Invited */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['TeamMember'];
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/team/invites/{userId}/resend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send the invitation again (new link, old one stops working; 60 s cooldown) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sent */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Accepted'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/team/invites/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a pending invitation */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/team/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a member (team.remove) — their sessions end */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Change role and/or enable / disable a member (team.update) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @enum {string} */
            roleKey?: 'admin' | 'manager' | 'agent' | 'viewer';
            /** @enum {string} */
            status?: 'active' | 'disabled';
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['TeamMember'];
            };
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/v1/team/transfer-ownership': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Owner only: make an active admin the owner (you become admin); needs your password */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            userId: string;
            /** Format: password */
            password: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: {
                ownerId: string;
              };
            };
          };
        };
        /** @description Missing / invalid / expired token (AUTH_UNAUTHENTICATED, AUTH_TOKEN_EXPIRED) */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Missing permission, disabled user, suspended account or impersonation block */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Not found in this account (RESOURCE_NOT_FOUND) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Conflict (CONFLICT_DUPLICATE / CONFLICT_INVALID_STATE) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/invite-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Details of a pending invitation (for the accept page) */
    get: {
      parameters: {
        query: {
          token: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['InviteInfo'];
            };
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/accept-invite': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept an invitation: set a password and sign in */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            token: string;
            /** Format: password */
            password: string;
            name?: string;
          };
        };
      };
      responses: {
        /** @description Signed in (sets the cav_rt cookie) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AuthSession'];
            };
          };
        };
        /** @description Validation failed / invalid code (VALIDATION_FAILED, AUTH_CODE_INVALID) */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
        /** @description Rate limited / too many attempts (RATE_LIMITED, AUTH_TOO_MANY_ATTEMPTS) — see Retry-After */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/system/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Service name, version and runtime */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description App info */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {boolean} */
              success: true;
              data: components['schemas']['AppInfo'];
            };
          };
        };
        /** @description Unexpected error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorDetail: {
      /** @example phone */
      path: string;
      /** @example Must be an E.164 number */
      message: string;
    };
    ErrorEnvelope: {
      /** @enum {boolean} */
      success: false;
      error: {
        /** @example VALIDATION_FAILED */
        code: string;
        /** @example Some fields are invalid. */
        message: string;
        details?: components['schemas']['ErrorDetail'][];
        /** @example req_8f2c1a */
        requestId: string;
      };
    };
    OffsetPageMeta: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
    CursorPageMeta: {
      nextCursor: string | null;
      hasMore: boolean;
    };
    Session: {
      /** @description Session (refresh family) id */
      id: string;
      userAgent: string | null;
      ip: string | null;
      createdAt: string;
      lastUsedAt: string;
      current: boolean;
    };
    Accepted: {
      /** @example Check your email for a verification code. */
      message: string;
    };
    PublicUser: {
      id: string;
      name: string;
      email: string;
      phone: string | null;
      /** @enum {string} */
      status: 'invited' | 'active' | 'disabled';
      emailVerifiedAt: string | null;
      lastLoginAt: string | null;
      /** @enum {string|null} */
      platformRole: 'superadmin' | null;
      createdAt: string;
    };
    PublicAccount: {
      id: string;
      name: string;
      slug: string;
      /** @enum {string} */
      status: 'active' | 'suspended';
      suspendReason: string | null;
      ownerId: string | null;
      isPlatform: boolean;
      timezone: string;
      country: string;
      /** @enum {string} */
      defaultLanguage: 'hi' | 'en' | 'hinglish';
      settings: {
        callingWindow: {
          /** @example 09:00 */
          start: string;
          /** @example 19:00 */
          end: string;
          /**
           * @example [
           *       1,
           *       2,
           *       3,
           *       4,
           *       5,
           *       6
           *     ]
           */
          days: number[];
        };
        recordingEnabled: boolean;
        aiDisclosureEnabled: boolean;
      };
      createdAt: string;
    };
    AuthMe: {
      user: components['schemas']['PublicUser'];
      account: components['schemas']['PublicAccount'];
      role: {
        key: string;
        name: string;
      };
      permissions: string[];
      impersonation: {
        impersonatorId: string;
        expiresAt: string;
      } | null;
    };
    AuthSession: {
      accessToken: string;
      /** @example 900 */
      expiresIn: number;
      user: components['schemas']['PublicUser'];
      account: components['schemas']['PublicAccount'];
      role: {
        key: string;
        name: string;
      };
      permissions: string[];
      impersonation: {
        impersonatorId: string;
        expiresAt: string;
      } | null;
    };
    AuditEntry: {
      id: string;
      /** @enum {string} */
      action:
        | 'account.created'
        | 'account.updated'
        | 'account.ownership_transferred'
        | 'account.suspended'
        | 'account.enabled'
        | 'auth.email_verified'
        | 'auth.login'
        | 'auth.login_failed'
        | 'auth.logout'
        | 'auth.logout_all'
        | 'auth.session_revoked'
        | 'auth.refresh_reuse_detected'
        | 'auth.password_reset_requested'
        | 'auth.password_reset'
        | 'auth.password_changed'
        | 'team.invited'
        | 'team.invite_resent'
        | 'team.invite_revoked'
        | 'team.invite_accepted'
        | 'team.role_changed'
        | 'team.disabled'
        | 'team.enabled'
        | 'team.removed'
        | 'apikey.created'
        | 'apikey.revoked'
        | 'admin.impersonation_started'
        | 'admin.impersonation_stopped';
      actor: {
        /** @enum {string} */
        type: 'user' | 'api_key' | 'system';
        id: string | null;
        name: string | null;
        impersonatorId: string | null;
        platform: boolean;
      };
      target: {
        type: string;
        id: string | null;
      } | null;
      meta: {
        [key: string]: unknown;
      } | null;
      ip: string | null;
      at: string;
    };
    AdminAccountRow: {
      id: string;
      name: string;
      slug: string;
      /** @enum {string} */
      status: 'active' | 'suspended';
      ownerEmail: string | null;
      usersCount: number;
      createdAt: string;
    };
    AdminAccountDetail: {
      account: components['schemas']['PublicAccount'];
      owner: components['schemas']['PublicUser'] & (Record<string, never> | null);
      usersCount: number;
      usersByStatus: {
        invited: number;
        active: number;
        disabled: number;
      };
      recentAudit: components['schemas']['AuditEntry'][];
    };
    ApiKey: {
      id: string;
      name: string;
      /** @example cav_live_ab12 */
      prefix: string;
      scopes: string[];
      lastUsedAt: string | null;
      revokedAt: string | null;
      createdBy: string;
      createdAt: string;
    };
    CreatedApiKey: {
      apiKey: components['schemas']['ApiKey'];
      /** @description The full key — shown only once, store it now. */
      key: string;
    };
    Health: {
      /** @enum {string} */
      status: 'ok';
      /** @example 3600 */
      uptimeSec: number;
    };
    Readiness: {
      /** @enum {string} */
      status: 'ready';
      /**
       * @example {
       *       "mongo": "up",
       *       "redis": "up"
       *     }
       */
      checks: {
        [key: string]: 'up';
      };
    };
    RbacCatalog: {
      permissions: {
        /** @example team.invite */
        key: string;
        /** @example Team */
        group: string;
        description: string;
      }[];
      roles: {
        /** @enum {string} */
        key: 'owner' | 'admin' | 'manager' | 'agent' | 'viewer';
        name: string;
        permissions: string[];
      }[];
    };
    WsTicket: {
      /** @example wst_q8V… */
      ticket: string;
      expiresAt: string;
    };
    TeamMember: {
      id: string;
      name: string;
      email: string;
      phone: string | null;
      /** @enum {string} */
      status: 'invited' | 'active' | 'disabled';
      role: {
        key: string;
        name: string;
      };
      isOwner: boolean;
      lastLoginAt: string | null;
      inviteExpiresAt: string | null;
      createdAt: string;
    };
    InviteInfo: {
      email: string;
      name: string;
      accountName: string;
      inviterName: string;
      roleName: string;
    };
    AppInfo: {
      /** @example cell-ai-voicebot-backend */
      name: string;
      /** @example 0.0.1 */
      version: string;
      /** @example v24.19.0 */
      node: string;
      /** @example development */
      env: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
