// Generates src/services/api/schema.gen.ts from the backend OpenAPI spec (ADR 0029).
// Spec path: $OPENAPI_SPEC, or the sibling backend repo by default.
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';
import * as prettier from 'prettier';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const specPath = path.resolve(
  root,
  process.env.OPENAPI_SPEC ?? '../cell-ai-voicebot-backend/openapi/openapi.json',
);
const outFile = path.join(root, 'src/services/api/schema.gen.ts');

if (!existsSync(specPath)) {
  console.error(
    `OpenAPI spec not found: ${specPath}\nRun "npm run gen:openapi" in the backend repo, or set OPENAPI_SPEC.`,
  );
  process.exit(1);
}

const ast = await openapiTS(pathToFileURL(specPath));
const header =
  '// AUTO-GENERATED by `npm run gen:api` from the backend OpenAPI spec — do not edit.\n' +
  '// Source of truth: cell-ai-voicebot-backend/openapi/openapi.json (ADR 0029).\n\n';
const options = (await prettier.resolveConfig(outFile)) ?? {};
const formatted = await prettier.format(header + astToString(ast), {
  ...options,
  parser: 'typescript',
});
writeFileSync(outFile, formatted);
console.info(`API types written to ${path.relative(root, outFile)}`);
